//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNWT
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_order
    {
        public int idfood_order { get; set; }
        public string order_name { get; set; }
        public System.DateTime oder_date { get; set; }
        public int amount { get; set; }
        public float order_price { get; set; }
        public int user_iduser { get; set; }
        public int food_menu_idfood { get; set; }
    
        public virtual food_menu food_menu { get; set; }
        public virtual user user { get; set; }
    }
}
