//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNWT
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int idimage { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public int resource_type_idresource_type { get; set; }
    
        public virtual resource_type resource_type { get; set; }
    }
}
