//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNWT
{
    using System;
    using System.Collections.Generic;
    
    public partial class keycard
    {
        public keycard()
        {
            this.resource = new HashSet<resource>();
        }
    
        public int idkeycard { get; set; }
        public string number { get; set; }
        public string access_identifier { get; set; }
    
        public virtual ICollection<resource> resource { get; set; }
    }
}
