//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNWT
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource
    {
        public int idresource { get; set; }
        public string name { get; set; }
        public byte[] occupied { get; set; }
        public byte[] available { get; set; }
        public string availability_status { get; set; }
        public Nullable<System.DateTime> availability_date { get; set; }
        public int resource_type_idresource_type { get; set; }
        public int keycard_idkeycard { get; set; }
        public int user_iduser { get; set; }
    
        public virtual keycard keycard { get; set; }
        public virtual resource_type resource_type { get; set; }
        public virtual user user { get; set; }
    }
}
