//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNWT
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_type
    {
        public resource_type()
        {
            this.image = new HashSet<image>();
            this.resource = new HashSet<resource>();
        }
    
        public int idresource_type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public float price { get; set; }
        public int qunatity { get; set; }
    
        public virtual ICollection<image> image { get; set; }
        public virtual ICollection<resource> resource { get; set; }
    }
}
